name: main-terraform-workflow
on:
  push:
    branches: [ main ]
defaults:
  run:
    working-directory: ./infra
concurrency:
  group: terraform
  cancel-in-progress: false
jobs:
  plan-infra-development:
    uses: ./.github/workflows/plan.yaml@ref
    with:
      TERRAFORM_VERSION: "1.7.5"
      TF_VAR_env: development
      TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
      TF_STATE_BUCKET_REGION: ${{ secrets.TF_STATE_BUCKET_REGION }}
    secrets:
      AWS_CLI_ASSUME_ROLE: ${{ secrets.AWS_CLI_ASSUME_ROLE_DEVELOPMENT }}
  
  apply-infra-development:
    uses: ./.github/workflows/apply.yaml@ref
    needs: plan-infra-development
    with:
      TERRAFORM_VERSION: "1.7.5"
      TF_VAR_env: development
      TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
      TF_STATE_BUCKET_REGION: ${{ secrets.TF_STATE_BUCKET_REGION }}
    secrets:
      AWS_CLI_ASSUME_ROLE: ${{ secrets.AWS_CLI_ASSUME_ROLE_DEVELOPMENT }}
  
  plan-infra-staging:
    uses: ./.github/workflows/plan.yaml@ref
    needs: apply-infra-development
    with:
      TERRAFORM_VERSION: "1.7.5"
      TF_VAR_env: staging
      TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
      TF_STATE_BUCKET_REGION: ${{ secrets.TF_STATE_BUCKET_REGION }}
    secrets:
      AWS_CLI_ASSUME_ROLE: ${{ secrets.AWS_CLI_ASSUME_ROLE_STAGING }}
  
  apply-infra-staging:
    uses: ./.github/workflows/apply.yaml@ref
    needs: plan-infra-staging
    with:
      TERRAFORM_VERSION: "1.7.5"
      TF_VAR_env: staging
      TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
      TF_STATE_BUCKET_REGION: ${{ secrets.TF_STATE_BUCKET_REGION }}
    secrets:
      AWS_CLI_ASSUME_ROLE: ${{ secrets.AWS_CLI_ASSUME_ROLE_STAGING }}
