name: main-terraform-workflow
on:
  push:
    branches: [ main ]
concurrency:
  group: terraform
  cancel-in-progress: false

defaults:
  run:
    working-directory: infra

jobs:
  plan-infra-development:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
      - uses: yashrajdighe/terraform-aws-deployment/actions/plan@main
        with:
          TERRAFORM_VERSION: "1.7.5"
          TF_VAR_env: development
          AWS_CLI_ASSUME_ROLE: ${{ secrets.AWS_CLI_ASSUME_ROLE_DEVELOPMENT }}
          TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
          TF_STATE_BUCKET_REGION: ${{ secrets.TF_STATE_BUCKET_REGION }}
  
  apply-infra-development:
    needs: plan-infra-development
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
      - uses: yashrajdighe/terraform-aws-deployment/actions/apply@main
        with:
          TERRAFORM_VERSION: "1.7.5"
          TF_VAR_env: development
          AWS_CLI_ASSUME_ROLE: ${{ secrets.AWS_CLI_ASSUME_ROLE_DEVELOPMENT }}
          TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
          TF_STATE_BUCKET_REGION: ${{ secrets.TF_STATE_BUCKET_REGION }}
  
  plan-infra-staging:
    needs: apply-infra-development
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read 
    steps:
      - uses: yashrajdighe/terraform-aws-deployment/actions/plan@main
        with:
          TERRAFORM_VERSION: "1.7.5"
          TF_VAR_env: staging
          AWS_CLI_ASSUME_ROLE: ${{ secrets.AWS_CLI_ASSUME_ROLE_STAGING }}
          TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
          TF_STATE_BUCKET_REGION: ${{ secrets.TF_STATE_BUCKET_REGION }}
  
  apply-infra-staging:
    needs: plan-infra-staging
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read 
    steps:
      - uses: yashrajdighe/terraform-aws-deployment/actions/apply@main
        with:
          TERRAFORM_VERSION: "1.7.5"
          TF_VAR_env: staging
          AWS_CLI_ASSUME_ROLE: ${{ secrets.AWS_CLI_ASSUME_ROLE_STAGING }}
          TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
          TF_STATE_BUCKET_REGION: ${{ secrets.TF_STATE_BUCKET_REGION }}
