name: pr-terraform-workflow
on:
  pull_request:
    branches: [ main ]
defaults:
  run:
    working-directory: ./infra
concurrency:
  group: terraform
  cancel-in-progress: false
jobs:
  plan-infra-development:
    uses: ./.github/terraform/plan.yaml
    with:
      TERRAFORM_VERSION: "1.7.5"
      TF_VAR_env: development
      TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
      TF_STATE_BUCKET_REGION: ${{ secrets.TF_STATE_BUCKET_REGION }}
    secrets:
      AWS_CLI_ASSUME_ROLE: ${{ secrets.AWS_CLI_ASSUME_ROLE_DEVELOPMENT }}
  
  plan-infra-staging:
    uses: ./.github/terraform/plan.yaml
    needs: plan-infra-development
    with:
      TERRAFORM_VERSION: "1.7.5"
      TF_VAR_env: staging
      TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
      TF_STATE_BUCKET_REGION: ${{ secrets.TF_STATE_BUCKET_REGION }}
    secrets:
      AWS_CLI_ASSUME_ROLE: ${{ secrets.AWS_CLI_ASSUME_ROLE_STAGING }}
