name: terraform-plan
on: workflow_dispatch
defaults:
  run:
    working-directory: ./infra
jobs:
  plan-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    environment: development
    env:
      TF_VAR_env: development
      TF_VAR_assume_role: ${{ secrets.AWS_CLI_ASSUME_ROLE }}
      AWS_ACCESS_KEY_ID: ${{ steps.aws-cli-creds.outputs.aws-access-key-id }}
      AWS_SECRET_ACCESS_KEY: ${{ steps.aws-cli-creds.outputs.aws-secret-access-key }}
    steps:
    - name: Configure AWS Credentials
      id: aws-cli-creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_CLI_ASSUME_ROLE }}
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.5"
        terraform_wrapper: false
        cli_config_credentials_token: ${{ secrets.TF_CLOUD_API_TOKEN }}
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
    - name: Terraform Init
      id: init
      run: terraform init
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
