name: pr-terraform-workflow
on:
  pull_request:
    branches: [ main ]
concurrency:
  group: terraform
  cancel-in-progress: false

jobs:
  plan-infra-development:
    uses: yashrajdighe/actions/plan@v1
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    with:
      TERRAFORM_VERSION: "1.7.5"
      TF_VAR_env: development
      AWS_CLI_ASSUME_ROLE: ${{ secrets.AWS_CLI_ASSUME_ROLE_DEVELOPMENT }}
      TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
      TF_STATE_BUCKET_REGION: ${{ secrets.TF_STATE_BUCKET_REGION }}
  
  plan-infra-staging:
    uses: yashrajdighe/actions/plan@v1
    needs: plan-infra-development
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    with:
      TERRAFORM_VERSION: "1.7.5"
      TF_VAR_env: staging
      AWS_CLI_ASSUME_ROLE: ${{ secrets.AWS_CLI_ASSUME_ROLE_STAGING }}
      TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
      TF_STATE_BUCKET_REGION: ${{ secrets.TF_STATE_BUCKET_REGION }}
